### ISSUE TITLE
option to use hg instead of git

### ISSUE THREAD

**Issue by powerman** [miyagawa/Dist-Milla#15]
hg works nicely with github nowadays (using hg-git plugin and workflow with bookmarks instead of named branches), so it makes sense for Milla to support both.

I've no previous experience with Dist::Zilla (exactly because of reasons you've listed in Milla's doc), so I've no idea is switching from git to hg is just a matter of adding something trivial to dist.ini, or it require forking Milla and rewriting hardcoded things in many places (at least I've seen embedded default .gitignore file in Milla's source).

So, if you don't like to add hg support yourself, please at least give me some basic directions what/how should be done and how complex you expect this task to be.

**Comment by miyagawa** [comment]
not sure if you or anyone else is still interested in this, but if you really want to support this, the right way is to add an option to MillaBundle (like `installer` already does) and loads a different set of modules for Mercurial rather than Git in there. 

I'm closing this issue for now, but if someone wants to work on it, feel free to open a pull request.

**Comment by powerman** [comment]
No, I'm not interested anymore. I give up and switched to git. :(

**Comment by miyagawa** [comment]
well that's :) because it makes a lot of things easier.
