### ISSUE TITLE
Should require Test::Pod 1.41

### ISSUE THREAD

**Issue by wollmers** [miyagawa/Dist-Milla#34]
Dist::Zilla::Plugin::PodSyntaxTests creates tests, which 

     use Test::Pod 1.41;

Thus Dist::Milla should declare 

     requires 'Test::Pod', '1.41';

**Comment by miyagawa** [comment]
It's [already declared](https://metacpan.org/source/MIYAGAWA/Dist-Milla-v1.0.14/META.json#L40) with the dependency by the plugin itself when exporting its prereqs.

**Comment by miyagawa** [comment]
Please report issues like this to upstream, individual plugin rather than on Milla.

That being said, I think your problem is similar to what I've stated at https://github.com/karenetheridge/Dist-Zilla-Plugin-Test-CleanNamespaces/pull/1 - a bunch of Test::* plugins created by dzil only declare its deps for testing or develop requires, so they won't be installed by end users until you run `dzil test` or `milla test` (same command).

There's no correct way to address this issue, since these modules are not required by the regular "users" of dzil or milla. One thing they can do with dzil I think is to create a new command similar to `dzil authordeps` that creates the merged list of develop requires for these plugins, which you can then pipe to cpanm.

Specifically for Milla, you can run: `cpanm --installdeps --with-develop Milla` to get all of its develop deps, but that doesn't work for extra Test:: plugins if you add to it.

**Comment by karenetheridge** [comment]
The plugin does inject a 'develop requires' prerq for Test::Pod: https://github.com/rjbs/Dist-Zilla/pull/123

>  One thing they can do with dzil I think is to create a new command similar to dzil authordeps that creates the merged list of develop requires for these plugins, which you can then pipe to cpanm.

See Dist::Zilla::App::Command::stale; you can also do `dzil listdeps --author --missing`

**Comment by miyagawa** [comment]
@karenetheridge `listdeps --author` does look like what I discussed above. It sounds too similar to `authordeps` and the difference could be a bit confusing though.

**Comment by wollmers** [comment]
@karenetheridge Thanks for the hint. 

I will prefer

    dzil listdeps --author --missing | cpanm

not installing more than needed.

**Comment by wollmers** [comment]
@miyagawa Reading the sources of the involved components again and again, I cannot locate the best solution for the issue.

I am not happy to leave this as RTFM, but running manually 

    milla test --all

will trigger the problem earlier.

**Comment by miyagawa** [comment]
`dzil listdeps --author --missing | cpanm` will install all the missing modules that you need as a developer for the module. 

> `milla test --all`
> will trigger the problem earlier.

not after the `dzil listdeps --author | cpanm` right? 

I'm happy to give a documentation/tutorial update to point to for Milla users, but this is ultimately an issue for dzil since Milla doesn't have anything to do with this.
